/*
 *
 * Title: Line Follower
 * Author: Anjuchan and Wonchu
 *
 * We have to figure out which surface that we will be testing the robot
 * since the reflected brightness is different based on all different 
 * materials and places 
 *
 * PLEASE DO NOT ERASE 
 *
 * */
#pragma config(Sensor, S1,     ,               sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Motor,  motorA,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#define TURN_SPEED 20
#define BASE_SPEED 10
#define DELAY_TIME 80

task main()
{

	while(true){

	 	motor[leftMotor] = BASE_SPEED;
	 	motor[rightMotor] = BASE_SPEED;
		
		//displayCenteredBigTextLine(4, "%d", sense);
		//delay(1000);
		//eraseDisplay();
    delay(DELAY_TIME);
		int sense = 0;
		sense = SensorValue[S1];
		
		float const TURN_DAMPENER = 30;
		int turnLeftCalled = 0; 
		int turnRightCalled = 0;
		
    if(sense > 111) {
			turnLeftCalled++;
			turnRightCalled = 0;
			motor[leftMotor] = -TURN_SPEED - turnLeftCalled * TURN_DAMPENER;
			motor[rightMotor] = TURN_SPEED + turnLeftCalled * TURN_DAMPENER;
			delay(DELAY_TIME);
		}
		if(sense < 111){
			turnRightCalled++;
			turnLeftCalled = 0;
			motor[leftMotor] = TURN_SPEED + turnRightCalled * TURN_DAMPENER;
			motor[rightMotor] = -TURN_SPEED - turnRightCalled * TURN_DAMPENER;
		  delay(DELAY_TIME);
		}
	}
}