#pragma config(Sensor, S1,     ,               sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S2,     sonic,          sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          senseMotor,      tmotorEV3_Large, PIDControl, encoder)
// initialize touch sensors

/*
 * Title: Sumobot
 * Author: Anjan and Wonchul
 *
 * !!Code automatically generated by 'ROBOTC' configuration wizard!!
 */

task main()
{
    while(1){
        // code for turning sensor arm
        // remember to reset motor
        
        :wq



    }
}
